#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RPC_URL="${CLAWCHAIN_EVM_RPC_URL:-http://127.0.0.1:8545}"
CHAIN_ID="${CLAWCHAIN_EVM_CHAIN_ID:-31337}"
MANIFEST_PATH="${CLAWCHAIN_EVM_MANIFEST_PATH:-$ROOT_DIR/runs/clawchain_chain_probe/deployment.json}"
SOURCE_PATH="$ROOT_DIR/contracts/CommitmentAnchor.sol"
ABI_PATH="$ROOT_DIR/contracts/CommitmentAnchor.abi.json"
FOUNDRY_IMAGE="${CLAWCHAIN_FOUNDRY_IMAGE:-ghcr.io/foundry-rs/foundry:latest}"
DEPLOYER_PRIVATE_KEY="${CLAWCHAIN_DEPLOYER_PRIVATE_KEY:-}"

if [[ -z "$DEPLOYER_PRIVATE_KEY" ]]; then
  cat >&2 <<EOF
CLAWCHAIN_DEPLOYER_PRIVATE_KEY is required to deploy CommitmentAnchor.
EOF
  exit 1
fi

cd "$ROOT_DIR"
if command -v forge >/dev/null 2>&1; then
  OUTPUT="$(forge create contracts/CommitmentAnchor.sol:CommitmentAnchor --rpc-url "$RPC_URL" --private-key "$DEPLOYER_PRIVATE_KEY" --broadcast 2>&1)"
elif command -v docker >/dev/null 2>&1; then
  OUTPUT="$(
    docker run --rm \
      --network host \
      --user "$(id -u):$(id -g)" \
      -v "$ROOT_DIR:/app" \
      -w /app \
      -e CLAWCHAIN_DEPLOYER_PRIVATE_KEY="$DEPLOYER_PRIVATE_KEY" \
      -e HOME=/tmp \
      -e FOUNDRY_DISABLE_NIGHTLY_WARNING=1 \
      --entrypoint /bin/sh \
      "$FOUNDRY_IMAGE" \
      -lc "forge create contracts/CommitmentAnchor.sol:CommitmentAnchor --rpc-url \"$RPC_URL\" --private-key \"$DEPLOYER_PRIVATE_KEY\" --broadcast" 2>&1
  )"
else
  cat >&2 <<EOF
Neither local forge nor docker Foundry fallback is available.
EOF
  exit 1
fi
printf '%s\n' "$OUTPUT"

CONTRACT_ADDRESS="$(printf '%s\n' "$OUTPUT" | sed -n 's/.*Deployed to: \(0x[a-fA-F0-9]\{40\}\).*/\1/p' | tail -n 1)"
TX_HASH="$(printf '%s\n' "$OUTPUT" | sed -n 's/.*Transaction hash: \(0x[a-fA-F0-9]\+\).*/\1/p' | tail -n 1)"

if [[ -z "$CONTRACT_ADDRESS" ]]; then
  cat >&2 <<EOF
Failed to extract deployed contract address from forge output.
EOF
  exit 1
fi

export CLAWCHAIN_DEPLOYED_CHAIN_ID="$CHAIN_ID"
export CLAWCHAIN_DEPLOYED_RPC_URL="$RPC_URL"
export CLAWCHAIN_DEPLOYED_CONTRACT_ADDRESS="$CONTRACT_ADDRESS"
export CLAWCHAIN_DEPLOYED_SOURCE_PATH="$SOURCE_PATH"
export CLAWCHAIN_DEPLOYED_ABI_PATH="$ABI_PATH"
export CLAWCHAIN_DEPLOYED_MANIFEST_PATH="$MANIFEST_PATH"
export CLAWCHAIN_DEPLOYED_TX_HASH="$TX_HASH"

python - <<PY
import os
from pathlib import Path
from clawchain.runtime import EvmDeploymentManifest, write_evm_deployment_manifest

manifest = EvmDeploymentManifest(
    chain_id=int(os.environ["CLAWCHAIN_DEPLOYED_CHAIN_ID"]),
    rpc_url=os.environ["CLAWCHAIN_DEPLOYED_RPC_URL"],
    contract_address=os.environ["CLAWCHAIN_DEPLOYED_CONTRACT_ADDRESS"],
    source_path=os.environ["CLAWCHAIN_DEPLOYED_SOURCE_PATH"],
    abi_path=os.environ["CLAWCHAIN_DEPLOYED_ABI_PATH"],
    deploy_tx_hash=os.environ.get("CLAWCHAIN_DEPLOYED_TX_HASH") or None,
    notes="Generated by scripts/deploy_commitment_anchor.sh",
)
manifest_path = Path(os.environ["CLAWCHAIN_DEPLOYED_MANIFEST_PATH"])
write_evm_deployment_manifest(manifest_path, manifest)
print(manifest_path)
PY
